"""Added new features in Animal model: animal_name, animal_gender, animal_age, animal_size, animal_coatLength, animal_color

Revision ID: 6e210a22706d
Revises: 6eb5ea5b058d
Create Date: 2024-07-26 17:04:02.823723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e210a22706d'
down_revision: Union[str, None] = '6eb5ea5b058d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_types',
    sa.Column('post_type_id', sa.Integer(), nullable=False),
    sa.Column('post_type_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('post_type_id'),
    sa.UniqueConstraint('post_type_name')
    )
    op.add_column('animals', sa.Column('animal_name', sa.String(), nullable=True))
    op.add_column('animals', sa.Column('animal_gender', sa.String(), nullable=True))
    op.add_column('animals', sa.Column('animal_age', sa.Integer(), nullable=True))
    op.add_column('animals', sa.Column('animal_size', sa.String(), nullable=True))
    op.add_column('animals', sa.Column('animal_coatLength', sa.String(), nullable=True))
    op.add_column('animals', sa.Column('animal_color', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('post_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'posts', 'post_types', ['post_type_id'], ['post_type_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'post_type_id')
    op.drop_column('animals', 'animal_color')
    op.drop_column('animals', 'animal_coatLength')
    op.drop_column('animals', 'animal_size')
    op.drop_column('animals', 'animal_age')
    op.drop_column('animals', 'animal_gender')
    op.drop_column('animals', 'animal_name')
    op.drop_table('post_types')
    # ### end Alembic commands ###
